export default {
  NEXT_STEP: 'NEXT_STEP',
  PREVIOUS_STEP: 'PREVIOUS_STEP',
  REFRESH_TIMER: 'REFRESH_TIMER',
  RESET_A_WHOLE_FORM: 'RESET_A_WHOLE_FORM',
  NEXT_INNER_STEP: 'NEXT_INNER_STEP',
  TIMER_COUNTDOWN_START: 'TIMER_COUNTDOWN_START',

  SET_ERROR_MESSAGE: 'SET_ERROR_MESSAGE',
  SET_SUCCESS_MESSAGE: 'SET_SUCCESS_MESSAGE',

  START_MOBILE_SENT: 'START_MOBILE_SENT',
  SUCCESS_MOBILE_SENT: 'SUCCESS_MOBILE_SENT',
  FAILED_MOBILE_SENT: 'FAILED_MOBILE_SENT',

  START_VERIFICATION_CODE_SENT: 'START_VERIFICATION_CODE_SENT',
  SUCCESS_VERIFICATION_CODE_SENT: 'SUCCESS_VERIFICATION_CODE_SENT',
  FAILED_VERIFICATION_CODE_SENT: 'FAILED_VERIFICATION_CODE_SENT',

  ACTION_VERIFICATION_CODE_ENTERED: 'ACTION_VERIFICATION_CODE_ENTERED',
  ACTION_MOBILE_NUMBER_VERIFIED: 'ACTION_MOBILE_NUMBER_VERIFIED',

  ACTION_USER_FILLED_PERSONAL_DATA: 'ACTION_USER_FILLED_PERSONAL_DATA'
};
