export const APP_STORAGE_KEY = process.env.REACT_APP_APP_STORAGE_KEY;
export const CURRENT_USER_STORAGE_KEY = process.env.REACT_APP_CURRENT_USER_STORAGE_KEY;
export const REGISTRATION_STATE_KEY = process.env.REACT_APP_CURRENT_USER_STORAGE_KEY;
export const GRAPHQL_URL = process.env.REACT_APP_GRAPHQL_URL;

export const SMS_CODE_VERIFICATION_EXPIRE_SECONDS = 30;

export const USER_TYPE_BUYER = 1;
export const USER_TYPE_SELLER_PERSON = 3;
export const USER_TYPE_SELLER_COMPANY = 7;

